#this playbook will install the git on target machines and initialize Git repository on the target machines
---
- name: Installing git on the target servers 
  hosts: all
  become: yes
  tasks:
    - name: Install git
      apt:
        name: git
        state: present
    - name: Initialize Git repository
      command: git init

